-- MySQL Script generated by MySQL Workbench
-- Mon Jan 23 10:44:26 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shop_course_np_371_372_2023
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `shop_course_np_371_372_2023` ;

-- -----------------------------------------------------
-- Schema shop_course_np_371_372_2023
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop_course_np_371_372_2023` DEFAULT CHARACTER SET utf8 ;
USE `shop_course_np_371_372_2023` ;

-- -----------------------------------------------------
-- Table `shop_course_np_371_372_2023`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_course_np_371_372_2023`.`category` ;

CREATE TABLE IF NOT EXISTS `shop_course_np_371_372_2023`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_course_np_371_372_2023`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_course_np_371_372_2023`.`product` ;

CREATE TABLE IF NOT EXISTS `shop_course_np_371_372_2023`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `price` DECIMAL(9,2) NOT NULL,
  `image` VARCHAR(45) NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_category_idx` (`category_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_course_np_371_372_2023`.`attribute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_course_np_371_372_2023`.`attribute` ;

CREATE TABLE IF NOT EXISTS `shop_course_np_371_372_2023`.`attribute` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `unit` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_course_np_371_372_2023`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_course_np_371_372_2023`.`users` ;

CREATE TABLE IF NOT EXISTS `shop_course_np_371_372_2023`.`users` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_course_np_371_372_2023`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_course_np_371_372_2023`.`clients` ;

CREATE TABLE IF NOT EXISTS `shop_course_np_371_372_2023`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `age` INT NULL,
  `phone` INT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_course_np_371_372_2023`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_course_np_371_372_2023`.`address` ;

CREATE TABLE IF NOT EXISTS `shop_course_np_371_372_2023`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `bulding` VARCHAR(45) NOT NULL,
  `clients_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_address_clients1_idx` (`clients_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_course_np_371_372_2023`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_course_np_371_372_2023`.`order` ;

CREATE TABLE IF NOT EXISTS `shop_course_np_371_372_2023`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_created` DATETIME NULL,
  `payment` VARCHAR(45) NULL,
  `delivery` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `clients_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_clients1_idx` (`clients_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_course_np_371_372_2023`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_course_np_371_372_2023`.`roles` ;

CREATE TABLE IF NOT EXISTS `shop_course_np_371_372_2023`.`roles` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_course_np_371_372_2023`.`attribute_has_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_course_np_371_372_2023`.`attribute_has_product` ;

CREATE TABLE IF NOT EXISTS `shop_course_np_371_372_2023`.`attribute_has_product` (
  `attribute_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`attribute_id`, `product_id`),
  INDEX `fk_attribute_has_product1_product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_attribute_has_product1_attribute1_idx` (`attribute_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_course_np_371_372_2023`.`roles_has_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_course_np_371_372_2023`.`roles_has_users` ;

CREATE TABLE IF NOT EXISTS `shop_course_np_371_372_2023`.`roles_has_users` (
  `roles_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`roles_id`, `users_id`),
  INDEX `fk_roles_has_users_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_roles_has_users_roles1_idx` (`roles_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop_course_np_371_372_2023`.`product_has_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop_course_np_371_372_2023`.`product_has_order` ;

CREATE TABLE IF NOT EXISTS `shop_course_np_371_372_2023`.`product_has_order` (
  `product_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`product_id`, `order_id`),
  INDEX `fk_product_has_order1_order1_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_product_has_order1_product1_idx` (`product_id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
